import os
import json
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# 1. Load data
data_path = 'loan_approval_data.csv'
if not os.path.exists(data_path):
    # fallback to subfolder if running from workspace root
    data_path = 'loan_approval_classifier/loan_approval_data.csv'

loan_df = pd.read_csv(data_path)

# 2. Fit Imputers
categorial_cols = list(loan_df.select_dtypes(include='object').columns)
numerical_cols = list(loan_df.select_dtypes(include='number').columns)

num_imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
num_imputer.fit(loan_df[numerical_cols])
num_means = dict(zip(numerical_cols, num_imputer.statistics_))

cat_imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
cat_imputer.fit(loan_df[categorial_cols])
cat_modes = dict(zip(categorial_cols, cat_imputer.statistics_))

# Impute values
loan_df[numerical_cols] = num_imputer.transform(loan_df[numerical_cols])
loan_df[categorial_cols] = cat_imputer.transform(loan_df[categorial_cols])

# 3. Drop ID if exists
if 'Applicant_ID' in loan_df.columns:
    loan_df = loan_df.drop('Applicant_ID', axis=1)

# 4. Education level encoding
le_edu = LabelEncoder()
loan_df['Education_Level'] = le_edu.fit_transform(loan_df['Education_Level'])
edu_classes = list(le_edu.classes_)

# 5. Loan approved label encoding
le_approved = LabelEncoder()
loan_df['Loan_Approved'] = le_approved.fit_transform(loan_df['Loan_Approved'])

# 6. One-hot encoding of other categoricals
cols_to_encode = ['Employment_Status', 'Marital_Status', 'Loan_Purpose', 'Property_Area', 'Gender', 'Employer_Category']
ohe = OneHotEncoder(drop='first', sparse_output=False, handle_unknown='ignore')
ohe.fit(loan_df[cols_to_encode])

ohe_categories = {col: list(cats) for col, cats in zip(cols_to_encode, ohe.categories_)}

encoded = ohe.transform(loan_df[cols_to_encode])
encoded_df = pd.DataFrame(encoded, columns=ohe.get_feature_names_out(), index=loan_df.index)
loan_df_encoded = pd.concat([loan_df.drop(columns=cols_to_encode), encoded_df], axis=1)

# 7. Feature engineering
loan_df_encoded['DTI_Ratio_sq'] = loan_df_encoded['DTI_Ratio'] ** 2
loan_df_encoded['Credit_Score_sq'] = loan_df_encoded['Credit_Score'] ** 2
loan_df_encoded['Applicant_Income_log'] = np.log1p(loan_df_encoded['Applicant_Income'])

# Define X and y (note we drop raw DTI_Ratio and Credit_Score as in cell 63)
X = loan_df_encoded.drop(columns=['DTI_Ratio', 'Credit_Score', 'Loan_Approved'])
y = loan_df_encoded['Loan_Approved']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 8. Standardize
scaler = StandardScaler()
scaler.fit(X_train)

# 9. Train Model
lr = LogisticRegression()
lr.fit(scaler.transform(X_train), y_train)

# 10. Prepare JS Object
# Standard Deviation = sqrt(variance)
std_devs = np.sqrt(scaler.var_).tolist()

model_params = {
    'features': list(X.columns),
    'scaler': {
        'mean': scaler.mean_.tolist(),
        'std': std_devs
    },
    'model': {
        'coef': lr.coef_[0].tolist(),
        'intercept': float(lr.intercept_[0])
    },
    'imputers': {
        'numerical': {k: float(v) for k, v in num_means.items()},
        'categorical': {k: str(v) for k, v in cat_modes.items()}
    },
    'encoders': {
        'education_classes': edu_classes,
        'ohe_categories': ohe_categories
    }
}

# Write to model_params.js
js_content = f"// Automatically generated by export_model.py\nconst MODEL_PARAMS = {json.dumps(model_params, indent=2)};\n"

out_dir = os.path.dirname(data_path) if '/' in data_path or '\\' in data_path else '.'
out_path = os.path.join(out_dir, 'model_params.js')

with open(out_path, 'w', encoding='utf-8') as f:
    f.write(js_content)

print(f"Model parameters exported successfully to {out_path}!")
