// Automatically generated by export_model.py
const MODEL_PARAMS = {
  "features": [
    "Applicant_Income",
    "Coapplicant_Income",
    "Age",
    "Dependents",
    "Existing_Loans",
    "Savings",
    "Collateral_Value",
    "Loan_Amount",
    "Loan_Term",
    "Education_Level",
    "Employment_Status_Salaried",
    "Employment_Status_Self-employed",
    "Employment_Status_Unemployed",
    "Marital_Status_Single",
    "Loan_Purpose_Car",
    "Loan_Purpose_Education",
    "Loan_Purpose_Home",
    "Loan_Purpose_Personal",
    "Property_Area_Semiurban",
    "Property_Area_Urban",
    "Gender_Male",
    "Employer_Category_Government",
    "Employer_Category_MNC",
    "Employer_Category_Private",
    "Employer_Category_Unemployed",
    "DTI_Ratio_sq",
    "Credit_Score_sq",
    "Applicant_Income_log"
  ],
  "scaler": {
    "mean": [
      10910.02554342105,
      5094.864719736842,
      39.989722368421056,
      1.4543302631578945,
      1.9446552631578948,
      9953.86432894737,
      25002.175668421052,
      20440.30707631579,
      47.7,
      0.27375,
      0.5175,
      0.18875,
      0.08875,
      0.33875,
      0.18875,
      0.1875,
      0.1925,
      0.1775,
      0.1875,
      0.52625,
      0.62625,
      0.2025,
      0.14625,
      0.425,
      0.08625,
      0.14082909541551247,
      459630.49335936294,
      9.165887939619722
    ],
    "std": [
      4958.806305634875,
      2868.2235079598686,
      10.929601446859195,
      1.0665994957236982,
      1.3590723673579959,
      5699.333437244647,
      14123.2016080825,
      11174.127878417426,
      23.711389668258587,
      0.4458822013716179,
      0.4996936561534477,
      0.39130989956810447,
      0.2843825548447021,
      0.473284731953187,
      0.3913098995681045,
      0.3903123748998999,
      0.3942635539838802,
      0.382091284904537,
      0.3903123748998999,
      0.49931046203739815,
      0.48379844718642906,
      0.40186284973856445,
      0.3533566717921143,
      0.49434299833212975,
      0.2807328578916263,
      0.09966913728445635,
      93243.28313190119,
      0.5548347662660619
    ]
  },
  "model": {
    "coef": [
      -1.724758853707653,
      0.03526102508626336,
      0.0003597335105239419,
      -0.13697669786183783,
      0.05467291615923677,
      0.03887958011536461,
      -0.034078683001970284,
      -0.2697477594904186,
      -0.16342405251639047,
      -0.16949867288587642,
      -0.23964991470612843,
      -0.13914558952578202,
      -0.23478241735526928,
      0.05534133312319569,
      -0.21209338050720788,
      -0.2518389815720067,
      -0.18953613796366656,
      -0.03579778478656768,
      0.053119547910275795,
      0.20747204171330583,
      -0.32674776758571694,
      -0.022843041010025558,
      0.1883164123156243,
      0.09515501814512482,
      0.10001989261851779,
      -2.368398507602254,
      1.9549183290088232,
      2.39057956565874
    ],
    "intercept": -2.1334121615744377
  },
  "imputers": {
    "numerical": {
      "Applicant_ID": 501.22,
      "Applicant_Income": 10852.571578947369,
      "Coapplicant_Income": 5082.4557894736845,
      "Age": 39.97157894736842,
      "Dependents": 1.4747368421052631,
      "Credit_Score": 676.0336842105263,
      "Existing_Loans": 1.9505263157894737,
      "DTI_Ratio": 0.34726315789473683,
      "Savings": 9940.452631578948,
      "Collateral_Value": 24802.79263157895,
      "Loan_Amount": 20522.825263157894,
      "Loan_Term": 48.0
    },
    "categorical": {
      "Employment_Status": "Salaried",
      "Marital_Status": "Married",
      "Loan_Purpose": "Business",
      "Property_Area": "Urban",
      "Education_Level": "Graduate",
      "Gender": "Male",
      "Employer_Category": "Private",
      "Loan_Approved": "No"
    }
  },
  "encoders": {
    "education_classes": [
      "Graduate",
      "Not Graduate"
    ],
    "ohe_categories": {
      "Employment_Status": [
        "Contract",
        "Salaried",
        "Self-employed",
        "Unemployed"
      ],
      "Marital_Status": [
        "Married",
        "Single"
      ],
      "Loan_Purpose": [
        "Business",
        "Car",
        "Education",
        "Home",
        "Personal"
      ],
      "Property_Area": [
        "Rural",
        "Semiurban",
        "Urban"
      ],
      "Gender": [
        "Female",
        "Male"
      ],
      "Employer_Category": [
        "Business",
        "Government",
        "MNC",
        "Private",
        "Unemployed"
      ]
    }
  }
};
